### ISSUE TITLE
Capture The Flag [max 20 participants or teams]

### ISSUE THREAD

**Issue by EvelyneWauters** [NicoVermeir/DevLabs#1]
A Jeopardy style competition where your hacking skills will be put to the test. Join as a team or solo. 100 challenges ranging from cryptography, reversing, web security and forensics to gaining root access on remote servers. Suitable for beginners and more experienced players. Points are earned by hacking your way through the challenges and finding a 'flag' file or solution. Make sure to bring your laptop and optionally install wanted security related software.

**Comment by tspinoy** [comment]
Thijs Spinoy

**Comment by TomD011099** [comment]
Tom De bruyn

**Comment by seppeLenaerts** [comment]
Seppe Lenaerts, team with Tom De Bruyn if possible

**Comment by JoaOris** [comment]
Joa Oris, in team met Thijs Spinoy

**Comment by AhmadAlhajKarim** [comment]
Ahmad Alhaj Karim

**Comment by AitAbdel** [comment]
Ait Oujkal Abdellatif

**Comment by TomDeBacker** [comment]
Tom De Backer, Jens Van Reusel, Angelo Carly, Jarne Kerkaert

**Comment by redasaada** [comment]
Reda Saada, team with Tom De Bruyn if possible

**Comment by MichielMortier** [comment]
Michiel Mortier, team with Ahmad Alhaj Karim

**Comment by jordi5300** [comment]
Jordi Van der Poten in team met Jarni Naudts. Als er nog mensen bij willen laat maar weten :-)

**Comment by David-VD** [comment]
David Van Droogenbroeck
