### ISSUE TITLE
Flowlab (max 12 participants)

### ISSUE THREAD

**Issue by EvelyneWauters** [NicoVermeir/DevLabs#2]
We will dive into an agile session where we will explore how work 'works' in a system.  How does work FLOW through an organization? We create for you today a safe environment, to fail, test and try out and eventually  learn Flow principles in a different way than a classical training. Sounds all a little bit strange? Well that is normal as I don't want to give to many details upfront.  :-) 
I do guarantee you that it will be a good half day with a lot of learnings and collaboration.  

Look forward to meet you all!! 
Wendy & Benny
![f4997617-ab84-407b-86d7-4e5c66718e3c](https://user-images.githubusercontent.com/12492733/171869759-c7c0682f-90f1-4194-b434-e4ce7ebeeb99.jpg)

**Comment by WendyDupont** [comment]
Interesting and fun interactive way to learn about organizing work!

**Comment by JohanSchoubben** [comment]
Johan Schoubben

**Comment by koenvanderstraeten** [comment]
Koen Vanderstraeten

**Comment by Hade-Bressinck** [comment]
Hade Bressinck

**Comment by abernardinello** [comment]
Belaid Aliat

**Comment by DanielBijnens** [comment]
I will come
