### ISSUE TITLE
Software Architecture: Getting Started

### ISSUE THREAD

**Issue by EvelyneWauters** [NicoVermeir/DevLabs#3]
_Do we really need architecture in agile projects? What does an architect do? Can an architect help to make rapid, agile delivery sustainable in a constantly changing world?_

Software development has evolved. Agile is now the de-facto standard. The role of an architect in an agile project is very different than the typical role in a more classic waterfall approach. Using an updated interpretation of ‘viewpoints and perspectives’, this workshop will demonstrate how to make rapid, agile delivery sustainable in a constantly changing world. But make no mistake: this is a hands-on workshop. Roll your sleeves up and be prepared to learn while doing!

**This architectural afternoon will be guided by Bart Blommaerts.**

**Comment by TimRanson** [comment]
Tim Ranson

**Comment by jasperderoeckRD** [comment]
Jasper De Roeck

**Comment by tiled0203** [comment]
Timothy Leduc

**Comment by Bibibear** [comment]
Nicolas Rastel

**Comment by Thogor** [comment]
Thomas Goris

**Comment by simonvdb4** [comment]
Simon Van den Bossche

**Comment by jonasflament** [comment]
Jonas Flament

**Comment by ArneKnockaert** [comment]
Arne Knockaert

**Comment by yass1205** [comment]
Yassin El Kalai

**Comment by fremancoder** [comment]
Freddy Mangelschots

**Comment by lievenleuridan** [comment]
Lieven Leuridan

**Comment by daveln** [comment]
Dave Luyten

**Comment by kodjane** [comment]
Aimé Kodjane

**Comment by ghost** [comment]
Maxime Sauvage

**Comment by abernardinello** [comment]
Alexis Bernardinello

**Comment by ddoaj97** [comment]
Dieter Deforce
