### ISSUE TITLE
CSSSS [CSS Shiny Stuff]

### ISSUE THREAD

**Issue by EvelyneWauters** [NicoVermeir/DevLabs#4]
In 2021 and 2022 a lot of features/module updates have been added to CSS (e.g. subgrid, layers, sizing functions, ...) time to explore what these will add to your daily CSS workflow. 
This topic starts with a talk by Thomas Hertog and afterwards there is time to experiment with these brand new features!

**Comment by NickyFasoel** [comment]
Nicky Fasoel

**Comment by jeffreyvm** [comment]
Jeffrey Van Mulem

**Comment by LTielenRD** [comment]
Loic Tielen

**Comment by EllisRealdolmen** [comment]
Ellis De Clercq

**Comment by janolaerts** [comment]
Jan Olaerts

**Comment by koenapp** [comment]
Koen Appermont

**Comment by Legolerp** [comment]
Jeroen

**Comment by RR2511** [comment]
Ruth Reynders
